name: Deploy dev Resources to AWS (Terraform Infrastructure)

on:
  pull_request_target:
    types: [closed]
    branches: ["staging"]
    paths:
      - "Infrastructure/**"
      - "dev/**"

permissions:
  contents: read # Required for actions/checkout to fetch code

concurrency:
  group: terraform-infra-dev
  cancel-in-progress: false

env:
  TF_WORKING_DIR: ./dev

jobs:
  not-merged:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - run: echo "The PR was NOT merged"

  terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (staging after merge)
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      # âœ… Using Access Keys Instead of OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: WhoAmI in AWS
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}