name: Deploy Resources to Visionary Writings

# Trigger the workflow on pull request closure targeting the 'main' branch
on:
  pull_request_target:
    types:
      - closed
    branches:
      - "main"
    paths:
      - "Infrastructure/**"
      - "prod/**"

permissions:
  id-token: write # REQUIRED for OIDC
  contents: read # Needed to checkout the repo

env:
  TF_WORKING_DIR: ./prod

jobs:
  not-merged:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was NOT merged

  terraform:
    if: github.event.pull_request.merged == true
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Role needs to still be created in AWS IAM with trust relationship to GitHub OIDC provider
          role-to-assume: arn:aws:iam::724220526141:role/Disraptor_Terraform_Resource_Provisioning_Roleupdated
          role-session-name: github-actions-deploy
          aws-region: af-south-1 # or your region

      # verify AWS identity
      - name: WhoAmI in AWS
        run: aws sts get-caller-identity
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Example: Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Or any other AWS CLI / CDK / SAM commands here
      # - name: Deploy with Terraform
      #   run: terraform apply -auto-approve
