name: Deploy dev Resources to AWS (Terraform Infrastructure)

on:
  pull_request_target:
    types: [closed]
    branches: ["staging"]
    paths:
      - "s3-user/**"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-infra-main
  cancel-in-progress: false

env:
  TF_WORKING_DIR: ./s3-user

jobs:
  not-merged:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - run: echo "The PR was NOT merged"

  terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (main after merge)
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::724220526141:role/Disraptor_Terraform_Resource_Provisioning_Roleupdated
          role-session-name: github-actions-deploy
          aws-region: af-south-1

      - name: WhoAmI in AWS
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
