name: Deploy VPC for Visionary Writings on AWS.

# Trigger the workflow on pull request closure targeting the 'main' branch
on:
  pull_request_target:
    types:
      - closed
    branches:
      - "main"
    paths:
      - "components/Infrastructure/vpc"

permissions:
  id-token: write # REQUIRED for OIDC
  contents: read # Needed to checkout the repo

env:
  TF_WORKING_DIR: ./Infrastructure/vpc

jobs:
  not-merged:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was NOT merged

  terraform:
    if: github.event.pull_request.merged == true
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Role needs to still be created in AWS IAM with trust relationship to GitHub OIDC provider
          # role-to-assume: arn:aws:iam::123456789012:role/github-actions-deploy-role
          role-session-name: github-actions-deploy
          aws-region: af-south-1 # or your region

      # verify AWS identity
      - name: WhoAmI in AWS
        run: aws sts get-caller-identity
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Example: Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
